name: "Continuous Integration - Main/Release"
on:
  push:
    branches:
      - main
    paths:
      - src/paymentservice/**  

jobs:

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/paymentservice 
    steps:
      - uses: actions/checkout@v4
      - name: Cache Node.js modules
        uses: actions/cache@v4
        with:
          path: src/paymentservice/node_modules  
          key: ${{ runner.os }}-npm-${{ hashFiles('src/paymentservice/package-lock.json') }} 
          restore-keys: |
            ${{ runner.os }}-npm-
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: install dependencies
        run: |
         npm install
         npm ci
      - name: npm build
        run: npm run build

  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/paymentservice 
    steps:
      - uses: actions/checkout@v4
      - name: Cache Node.js modules
        uses: actions/cache@v4
        with:
          path: src/paymentservice/node_modules  
          key: ${{ runner.os }}-npm-${{ hashFiles('src/paymentservice/package-lock.json') }} 
          restore-keys: |
            ${{ runner.os }}-npm-
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: install dependencies
        run: |
         npm install
         npm ci
      - name: npm testing
        run: npm test

  linting:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/paymentservice  
    steps:
      - uses: actions/checkout@v4
      - name: Cache Node.js modules
        uses: actions/cache@v4
        with:
          path: src/paymentservice/node_modules  
          key: ${{ runner.os }}-npm-${{ hashFiles('src/paymentservice/package-lock.json') }} 
          restore-keys: |
            ${{ runner.os }}-npm-
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: install dependencies
        run: |
         npm install
         npm ci
         npm audit fix
      - name: npm lint
        run: npm run lint

  dockernize:
    needs:
      - linting
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          pwd
          ls
          cd src
          ls
          docker buildx build --platform linux/amd64 -t payment-service:latest src/paymentservice/Dockerfile