name: "Continuous Integration - Main/Release"
on:
  push:
    branches:
      - main
    paths:
      - src/paymentservice/**  # Added /** to include all files in directory

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/paymentservice  # Set default working directory
    steps:
      - uses: actions/checkout@v4
      - name: Cache Node.js modules
        uses: actions/cache@v4
        with:
          path: src/paymentservice/node_modules  # Corrected cache path
          key: ${{ runner.os }}-npm-${{ hashFiles('src/paymentservice/package-lock.json') }}  # Specific path
          restore-keys: |
            ${{ runner.os }}-npm-
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: install dependencies
        run: npm install
      - name: install dependencies
        run: npm ci
      - name: npm testing2
        run: npm test

  linting:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/paymentservice  # Set default working directory
    steps:
      - uses: actions/checkout@v4
      - name: Cache Node.js modules
        uses: actions/cache@v4
        with:
          path: src/paymentservice/node_modules  # Corrected cache path
          key: ${{ runner.os }}-npm-${{ hashFiles('src/paymentservice/package-lock.json') }}  # Specific path
          restore-keys: |
            ${{ runner.os }}-npm-
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: install dependencies
        run: npm install
      - name: install
        run: npm ci
      - name: npm lint
        run: npm run lint